version: 1
formatters:
  default:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: screenshots/logs/screenshot_bot_logs.log

loggers:
  mainLogger:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]